"""Add new models and extend existing ones

Revision ID: 7e668e235a45
Revises: 
Create Date: 2025-06-11 18:47:36.236061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e668e235a45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('is_like', sa.Boolean(), nullable=False))
    op.add_column('posts', sa.Column('privacy_level', sa.Enum('PUBLIC', 'FOLLOWERS', 'PRIVATE', name='privacylevel'), nullable=True))
    op.add_column('posts', sa.Column('comments_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('is_comments_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('following_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('posts_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'posts_count')
    op.drop_column('users', 'following_count')
    op.drop_column('users', 'followers_count')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.drop_column('posts', 'is_comments_enabled')
    op.drop_column('posts', 'comments_count')
    op.drop_column('posts', 'privacy_level')
    op.drop_column('likes', 'is_like')
    # ### end Alembic commands ###
