"""add_likes_dislikes_count_to_posts

Revision ID: ffce944d3a56
Revises: 35632529b63a
Create Date: 2025-06-19 19:55:04.212394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffce944d3a56'
down_revision: Union[str, None] = '35632529b63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes_count', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('dislikes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'dislikes_count')
    op.drop_column('posts', 'likes_count')
    # ### end Alembic commands ###
